### ISSUE TITLE
How should (n+1)sec re-act when there is unresolvable disagreement on the DoS status  a user?

### ISSUE THREAD

**Issue by vmon** [equalitie/np1sec#34]
There ways to confirm a malcious blocking users by checking digital signature etc. But there are situation arises that legimitely a user gets the traffic from the supposedly "DoSing" user and other doesn't? How should (n+1)sec should re-act in such situation?
1. Should we take no action?
2. Should we have a moderator and takes the side of the moderator? 
3. Should we break the room in two?
4. Should we act democratically? 

The solutions are ranked based on complexity of implementation.

**Comment by graphiclunarkid** [comment]
The protocol now handles DoS behaviour by breaking the room in two.
