### ISSUE TITLE
questions on np1sec_api.md

### ISSUE THREAD

**Issue by florianap** [equalitie/np1sec#41]
questions on https://github.com/equalitie/np1sec/blob/api-docs/doc/np1sec_api.md

* line 33: Once the process of creating a conversation is finished, the user is announced through the `RoomInterface::conversation_created` callback.

    Formerly "the user is let known" -- is "announced" correct? Or should it maybe "presented"/"introduced"?

* line 149: "To stay independent from the event loop it is used in as much as possible, users
of the library are required to implement few timer related function" -- what is "it" in "the event loop it is used in"?

* line 176: unlike the other 2 bullet points, this doesn't see to be an event. can you confirm it shouldn't be rephrased?

**Comment by inetic** [comment]
* line 33: "announced" isn't correct here. The "user" is known prior to the `conversation_created` callback (it is "myself"). Instead the callbacks tells the user that the conversation which he/she started creating has now been created.

* line 149: Yeah, it should have been: "To stay independent from the event loop it is used in (as much as possible), users of the library are..."

* This shouldn't be rephrased. But I shouldn't have used "Right after...", instead it should be "After ..." in both, the first and third bullets.
